---
- name: Create Samba configuration directory
  file:
    state: directory
    path: "{{ samba_config_dir }}"
    owner: root
    group: root
    mode: '0755'
  tags: samba

- name: Generate Samba configuration file
  template:
    src: smb.conf.j2
    dest: "{{ samba_config_file }}"
    owner: root
    mode: '0644'
  tags: samba

- name: Create Samba username map file
  template:
    dest: "{{ samba_username_map_file }}"
    src: smbusers.j2
    owner: root
    mode: '0644'
  when: samba_username_map is defined
  tags: samba
